# Generated by Django 4.2.4 on 2023-08-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
