# Generated by Django 4.2.4 on 2023-08-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTools', '0002_alter_tool_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
